### ISSUE TITLE
Multiple inputs using comma separated text

### ISSUE THREAD

**Issue by theojalba** [eth2353/ETHstaker.tax#17]
Can you support commas separated text for entering multiple inputs at once, namely entering multiple validator indices, multiple validator public keys and multiple ETH1 deposit addresses?

For example, if I have 3 validator indexes (e.g. 1001, 1002, 1003) now I have to:
1. Type the first index in - 1001.
2. Hit Add Another
3. Type the second index in - 1002.
4. Hit Add Another
5. Type the third index in - 1003.

Instead I would like to be able to put in a comma separated string, and have the code auto-expand them into separate entries.

1. Type the string 1001,1002,1003 into the first box.
2. Hit Add Another
3. Have the site show 3 input boxes, each with a separate index.

**Comment by eth2353** [comment]
That sounds reasonable, although it doesn't strike me as very intuitive behavior, but I'll give it some more thought.

Is the current alternative to inputting individual validators not suitable for you for some reason? The ETH1 deposit address(es) allow you to input multiple validators at once given they have the same deposit address. Do yours not have the same deposit address or has the deposit address been used for validators that you don't want to track?

I've also been thinking of simply storing the inputs in the browser storage and automatically loading them, that way the inputs would be remembered from the previous visit.

**Comment by theojalba** [comment]
> I've also been thinking of simply storing the inputs in the browser storage and automatically loading them, that way the inputs would be remembered from the previous visit.

👍  This is a good solution that works for me!

**Comment by gwenvador** [comment]
Please consider the initial request with comma separated address. It is much easier with higher number of validators, pub key or ETH address. Beaconchain does it better at https://beaconcha.in/user/rewards.

**Comment by eth2353** [comment]
> Beaconchain does it better

Oh no, we can't allow that can we? 😄


Just added support for comma-separated inputs to the website:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/70237279/232618591-606f28ac-f11f-4e3e-aa39-93a187c34160.png">

You can now enter a comma-separated list of values into every input field.

Let me know if you like it this way, enjoy!
