### ISSUE TITLE
Redis error when running make migrate

### ISSUE THREAD

**Issue by slavik0329** [eth2353/ETHstaker.tax#28]
I am getting this below error when running 'make migrate':

ERROR: for redis  Cannot start service redis: error while creating mount source path '/opt/eth2.tax/etc/redis.conf': mkdir /opt/eth2.tax: read-only file system

Everything else seems to install fine

**Comment by eth2353** [comment]
Seems like you solved it? Probably enough to adjust ABSOLUTE_ROOT_PATH in the `.env` file. I don't know of anyone else that is actually running this locally so you may run into other small issues.

Be aware that unless you make some modifications to only index your validators' data, running the entire stack will index all data and that currently takes up about 40-50GB of space.
